[package]
name = "dotfiles"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dotfiles"
path = "src/dotfiles.rs"

[dependencies]
copy_dir = "0.1.3"
home = "0.5.9"
runas = "1.2.0"
sysinfo = "0.30.12"
which = "6.0.1"
whoami = "1.5.1"
